version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: petstagram_db
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: