# Generated by Django 5.1.1 on 2025-11-20 21:12

import cloudinary_storage.storage
import petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='petstagram/pet_photos/', validators=[petstagram.photos.validators.FileSizeValidator(5)]),
        ),
    ]
