# Generated by Django 5.1.1 on 2025-04-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_like_to_photo'),
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_and_time_of_production']},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['date_and_time_of_production'], name='common_comm_date_an_49a3a2_idx'),
        ),
    ]
